---

- hosts: neutron_servers
  become: true
  tasks:

  - name: Install Neutron Package (Ubuntu)
    tags: neutron
    apt:
      name: 
        - neutron-server
        - neutron-plugin-ml2
        - neutron-linuxbridge-agent
        - neutron-l3-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent
        - python3-neutronclient
      state: latest
    when: ansible_distribution == "Ubuntu"
